Fixes for deepeval 3.9.4
There was a change made in deepeval 3.9.4 which caused a bunch of our
typing tests to fail.

The commit in question [1] fixes the type definition of the `model`
attribute in `BaseMetric`. Previously the class wasn't applying the
type, but it was just assigning it.

Now that this `model` attribute is properly typed, we're seeing some
pyright errors in our code because this attribute can now be `None`,
whereas previously it couldn't be.

I had a bit of a battle with pyright here. In our code we're
instantiating this `self.model` attribute using deepeval's
`initialize_model` method [2]. This method will always return a non-None
value, but because of the new type definition, the `self.model`
attribute is typed as being allowed to be `None`.

So when we come to call `self.model.a_generate`, we get a bunch of
errors:

```
absence_of_factual_contradictions.py:163:34 - error: "a_generate" is not a known attribute of "None"
```

First I tried to explicitly cast the `self.model` attribute, like so:

```
self.model: DeepEvalBaseLLM
self.model, self.using_native_model = initialize_model(model)
```

But that threw up more errors:

```
error: "model" overrides symbol of same name in class "BaseMetric"
    Variable is mutable so its type is invariant
      Override type "DeepEvalBaseLLM" is not the same as base type "DeepEvalBaseLLM | None" (reportIncompatibleVariableOverride)
```

Mutable attributes are invariant, so you can’t narrow their type in a subclass.

So it seems like the best solution here is to use an `assert` to please
the typechecker. It still doesn't feel ideal but it's the least invasive
change to make.

[1]: https://github.com/confident-ai/deepeval/commit/e538991
[2]: https://github.com/confident-ai/deepeval/blob/e538991/deepeval/metrics/utils.py#L533-L535